name: Tests
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install
        run: npm install
      - name: Check Lint
        run: npm run lint
      - name: Audit
        run: npm audit
      - name: Test
        run: npm test
        env:
          ULA_BASIC_AUTH: aWN0dTp2NzdzaHZ6Z2VQeVpwUm9pQ3dhTzNETXljZlVVN0xNcGM4SG03bjlt
          ULA_ENDPOINT: https://0xvvmwxd6e.execute-api.eu-west-1.amazonaws.com/dev/sessions
      - name: Coverage
        run: npm run coverage
        run: sed -i 's|SF:/home/runner/work/discipl-core-ula-server/discipl-core-ula-server/|SF:|g' coverage/lcov.info
      - name: Sonar
        run: sed -i 's|SF:/home/runner/work/discipl-core-ula-server/discipl-core-ula-server/|SF:|g' coverage/lcov.info
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}